/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubjectId = IDL.Nat;
export const CreateQuestionPayload = IDL.Record({
  'text' : IDL.Text,
  'subjectId' : SubjectId,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const QuestionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Question = IDL.Record({
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'subjectId' : SubjectId,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const CreateSubjectPayload = IDL.Record({
  'name' : IDL.Text,
  'timerMinutes' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'timerMinutes' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
});
export const AttemptId = IDL.Nat;
export const UserId = IDL.Principal;
export const QuizAttemptPublic = IDL.Record({
  'id' : AttemptId,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'answers' : IDL.Vec(IDL.Nat),
  'completed' : IDL.Bool,
  'studentPrincipal' : UserId,
  'scorePercentage' : IDL.Nat,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timeLimitMinutes' : IDL.Opt(IDL.Nat),
  'subjectId' : SubjectId,
});
export const StudentNameEntry = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
});
export const AttemptDetails = IDL.Record({
  'attempt' : QuizAttemptPublic,
  'correctAnswers' : IDL.Vec(IDL.Nat),
});
export const CertificateId = IDL.Nat;
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'completedAt' : Timestamp,
  'studentId' : UserId,
  'studentName' : IDL.Text,
  'subjectName' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'subjectId' : SubjectId,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'rank' : IDL.Nat,
  'totalAttempts' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const StudentProfilePublic = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'section' : IDL.Text,
  'registerNumber' : IDL.Text,
  'accentColor' : IDL.Text,
  'department' : IDL.Text,
  'registeredAt' : Timestamp,
  'enrollNumber' : IDL.Text,
});
export const StudentSummary = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'totalAttempts' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const QuestionPublic = IDL.Record({
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'subjectId' : SubjectId,
  'options' : IDL.Vec(IDL.Text),
});
export const SubjectWithStats = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'timerMinutes' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const SubmitAnswersPayload = IDL.Record({
  'attemptId' : AttemptId,
  'answers' : IDL.Vec(IDL.Nat),
});
export const SubmitQuizResult = IDL.Record({
  'attempt' : QuizAttemptPublic,
  'correctAnswers' : IDL.Vec(IDL.Nat),
});
export const UpdateQuestionPayload = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'subjectId' : SubjectId,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UpdateSubjectPayload = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'timerMinutes' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuestion' : IDL.Func([CreateQuestionPayload], [Question], []),
  'createSubject' : IDL.Func([CreateSubjectPayload], [Subject], []),
  'deleteQuestion' : IDL.Func([QuestionId], [IDL.Bool], []),
  'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
  'generateCertificateShareToken' : IDL.Func(
      [SubjectId],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getAllAttempts' : IDL.Func([], [IDL.Vec(QuizAttemptPublic)], ['query']),
  'getAllStudentNames' : IDL.Func([], [IDL.Vec(StudentNameEntry)], ['query']),
  'getAttemptDetails' : IDL.Func(
      [AttemptId],
      [IDL.Opt(AttemptDetails)],
      ['query'],
    ),
  'getAttemptsByStudent' : IDL.Func(
      [UserId],
      [IDL.Vec(QuizAttemptPublic)],
      ['query'],
    ),
  'getAttemptsBySubject' : IDL.Func(
      [SubjectId],
      [IDL.Vec(QuizAttemptPublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificateByToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttemptPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [StudentProfilePublic], []),
  'getSubjectCertificate' : IDL.Func(
      [SubjectId],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
  'listQuestionsBySubject' : IDL.Func(
      [SubjectId],
      [IDL.Vec(QuestionPublic)],
      ['query'],
    ),
  'listQuestionsWithAnswers' : IDL.Func(
      [SubjectId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'listSubjects' : IDL.Func([], [IDL.Vec(SubjectWithStats)], ['query']),
  'registerStudent' : IDL.Func([], [StudentProfilePublic], []),
  'startQuiz' : IDL.Func([SubjectId], [QuizAttemptPublic], []),
  'submitQuizAnswers' : IDL.Func(
      [SubmitAnswersPayload],
      [SubmitQuizResult],
      [],
    ),
  'updateMyAccentColor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMyDepartment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMyDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMyEnrollNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMyRegisterNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMySection' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateQuestion' : IDL.Func([UpdateQuestionPayload], [IDL.Bool], []),
  'updateSubject' : IDL.Func([UpdateSubjectPayload], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubjectId = IDL.Nat;
  const CreateQuestionPayload = IDL.Record({
    'text' : IDL.Text,
    'subjectId' : SubjectId,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const QuestionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Question = IDL.Record({
    'id' : QuestionId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'subjectId' : SubjectId,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const CreateSubjectPayload = IDL.Record({
    'name' : IDL.Text,
    'timerMinutes' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'timerMinutes' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
  });
  const AttemptId = IDL.Nat;
  const UserId = IDL.Principal;
  const QuizAttemptPublic = IDL.Record({
    'id' : AttemptId,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'answers' : IDL.Vec(IDL.Nat),
    'completed' : IDL.Bool,
    'studentPrincipal' : UserId,
    'scorePercentage' : IDL.Nat,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timeLimitMinutes' : IDL.Opt(IDL.Nat),
    'subjectId' : SubjectId,
  });
  const StudentNameEntry = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
  });
  const AttemptDetails = IDL.Record({
    'attempt' : QuizAttemptPublic,
    'correctAnswers' : IDL.Vec(IDL.Nat),
  });
  const CertificateId = IDL.Nat;
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'completedAt' : Timestamp,
    'studentId' : UserId,
    'studentName' : IDL.Text,
    'subjectName' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'subjectId' : SubjectId,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'rank' : IDL.Nat,
    'totalAttempts' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const StudentProfilePublic = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'section' : IDL.Text,
    'registerNumber' : IDL.Text,
    'accentColor' : IDL.Text,
    'department' : IDL.Text,
    'registeredAt' : Timestamp,
    'enrollNumber' : IDL.Text,
  });
  const StudentSummary = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'totalAttempts' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const QuestionPublic = IDL.Record({
    'id' : QuestionId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'subjectId' : SubjectId,
    'options' : IDL.Vec(IDL.Text),
  });
  const SubjectWithStats = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'timerMinutes' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const SubmitAnswersPayload = IDL.Record({
    'attemptId' : AttemptId,
    'answers' : IDL.Vec(IDL.Nat),
  });
  const SubmitQuizResult = IDL.Record({
    'attempt' : QuizAttemptPublic,
    'correctAnswers' : IDL.Vec(IDL.Nat),
  });
  const UpdateQuestionPayload = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'subjectId' : SubjectId,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UpdateSubjectPayload = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'timerMinutes' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuestion' : IDL.Func([CreateQuestionPayload], [Question], []),
    'createSubject' : IDL.Func([CreateSubjectPayload], [Subject], []),
    'deleteQuestion' : IDL.Func([QuestionId], [IDL.Bool], []),
    'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
    'generateCertificateShareToken' : IDL.Func(
        [SubjectId],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getAllAttempts' : IDL.Func([], [IDL.Vec(QuizAttemptPublic)], ['query']),
    'getAllStudentNames' : IDL.Func([], [IDL.Vec(StudentNameEntry)], ['query']),
    'getAttemptDetails' : IDL.Func(
        [AttemptId],
        [IDL.Opt(AttemptDetails)],
        ['query'],
      ),
    'getAttemptsByStudent' : IDL.Func(
        [UserId],
        [IDL.Vec(QuizAttemptPublic)],
        ['query'],
      ),
    'getAttemptsBySubject' : IDL.Func(
        [SubjectId],
        [IDL.Vec(QuizAttemptPublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificateByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttemptPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [StudentProfilePublic], []),
    'getSubjectCertificate' : IDL.Func(
        [SubjectId],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
    'listQuestionsBySubject' : IDL.Func(
        [SubjectId],
        [IDL.Vec(QuestionPublic)],
        ['query'],
      ),
    'listQuestionsWithAnswers' : IDL.Func(
        [SubjectId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listSubjects' : IDL.Func([], [IDL.Vec(SubjectWithStats)], ['query']),
    'registerStudent' : IDL.Func([], [StudentProfilePublic], []),
    'startQuiz' : IDL.Func([SubjectId], [QuizAttemptPublic], []),
    'submitQuizAnswers' : IDL.Func(
        [SubmitAnswersPayload],
        [SubmitQuizResult],
        [],
      ),
    'updateMyAccentColor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMyDepartment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMyDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMyEnrollNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMyRegisterNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMySection' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateQuestion' : IDL.Func([UpdateQuestionPayload], [IDL.Bool], []),
    'updateSubject' : IDL.Func([UpdateSubjectPayload], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };