/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttemptDetails {
  'attempt' : QuizAttemptPublic,
  'correctAnswers' : Array<bigint>,
}
export type AttemptId = bigint;
export interface CreateQuestionPayload {
  'text' : string,
  'subjectId' : SubjectId,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface CreateSubjectPayload {
  'name' : string,
  'description' : string,
}
export interface Question {
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'text' : string,
  'subjectId' : SubjectId,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface QuestionPublic {
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'text' : string,
  'subjectId' : SubjectId,
  'options' : Array<string>,
}
export interface QuizAttemptPublic {
  'id' : AttemptId,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'answers' : Array<bigint>,
  'completed' : boolean,
  'studentPrincipal' : UserId,
  'scorePercentage' : bigint,
  'score' : bigint,
  'totalQuestions' : bigint,
  'subjectId' : SubjectId,
}
export interface StudentProfilePublic {
  'principal' : UserId,
  'displayName' : string,
  'registeredAt' : Timestamp,
}
export interface StudentSummary {
  'principal' : UserId,
  'displayName' : string,
  'totalAttempts' : bigint,
  'averageScore' : bigint,
}
export interface Subject {
  'id' : SubjectId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export type SubjectId = bigint;
export interface SubjectWithStats {
  'id' : SubjectId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'questionCount' : bigint,
}
export interface SubmitAnswersPayload {
  'attemptId' : AttemptId,
  'answers' : Array<bigint>,
}
export interface SubmitQuizResult {
  'attempt' : QuizAttemptPublic,
  'correctAnswers' : Array<bigint>,
}
export type Timestamp = bigint;
export interface UpdateQuestionPayload {
  'id' : QuestionId,
  'text' : string,
  'subjectId' : SubjectId,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface UpdateSubjectPayload {
  'id' : SubjectId,
  'name' : string,
  'description' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuestion' : ActorMethod<[CreateQuestionPayload], Question>,
  'createSubject' : ActorMethod<[CreateSubjectPayload], Subject>,
  'deleteQuestion' : ActorMethod<[QuestionId], boolean>,
  'deleteSubject' : ActorMethod<[SubjectId], boolean>,
  'getAllAttempts' : ActorMethod<[], Array<QuizAttemptPublic>>,
  'getAttemptDetails' : ActorMethod<[AttemptId], [] | [AttemptDetails]>,
  'getAttemptsByStudent' : ActorMethod<[UserId], Array<QuizAttemptPublic>>,
  'getAttemptsBySubject' : ActorMethod<[SubjectId], Array<QuizAttemptPublic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAttempts' : ActorMethod<[], Array<QuizAttemptPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [StudentProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudents' : ActorMethod<[], Array<StudentSummary>>,
  'listQuestionsBySubject' : ActorMethod<[SubjectId], Array<QuestionPublic>>,
  'listQuestionsWithAnswers' : ActorMethod<[SubjectId], Array<Question>>,
  'listSubjects' : ActorMethod<[], Array<SubjectWithStats>>,
  'registerStudent' : ActorMethod<[], StudentProfilePublic>,
  'startQuiz' : ActorMethod<[SubjectId], QuizAttemptPublic>,
  'submitQuizAnswers' : ActorMethod<[SubmitAnswersPayload], SubmitQuizResult>,
  'updateMyDisplayName' : ActorMethod<[string], boolean>,
  'updateQuestion' : ActorMethod<[UpdateQuestionPayload], boolean>,
  'updateSubject' : ActorMethod<[UpdateSubjectPayload], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];