/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateQuestionPayload {
    text: string;
    subjectId: SubjectId;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export interface LeaderboardEntry {
    principal: UserId;
    displayName: string;
    rank: bigint;
    totalAttempts: bigint;
    averageScore: bigint;
}
export type Timestamp = bigint;
export interface StudentProfilePublic {
    principal: UserId;
    displayName: string;
    section: string;
    registerNumber: string;
    accentColor: string;
    department: string;
    registeredAt: Timestamp;
    enrollNumber: string;
}
export interface Certificate {
    id: CertificateId;
    completedAt: Timestamp;
    studentId: UserId;
    studentName: string;
    subjectName: string;
    score: bigint;
    totalQuestions: bigint;
    subjectId: SubjectId;
}
export interface UpdateQuestionPayload {
    id: QuestionId;
    text: string;
    subjectId: SubjectId;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export type AttemptId = bigint;
export interface QuestionPublic {
    id: QuestionId;
    createdAt: Timestamp;
    text: string;
    subjectId: SubjectId;
    options: Array<string>;
}
export type QuestionId = bigint;
export interface CreateSubjectPayload {
    name: string;
    timerMinutes?: bigint;
    description: string;
}
export type CertificateId = bigint;
export interface SubmitAnswersPayload {
    attemptId: AttemptId;
    answers: Array<bigint>;
}
export interface AttemptDetails {
    attempt: QuizAttemptPublic;
    correctAnswers: Array<bigint>;
}
export type UserId = Principal;
export interface UpdateSubjectPayload {
    id: SubjectId;
    name: string;
    timerMinutes?: bigint;
    description: string;
}
export interface SubjectWithStats {
    id: SubjectId;
    name: string;
    createdAt: Timestamp;
    timerMinutes?: bigint;
    description: string;
    questionCount: bigint;
}
export interface QuizAttemptPublic {
    id: AttemptId;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    answers: Array<bigint>;
    completed: boolean;
    studentPrincipal: UserId;
    scorePercentage: bigint;
    score: bigint;
    totalQuestions: bigint;
    timeLimitMinutes?: bigint;
    subjectId: SubjectId;
}
export interface StudentNameEntry {
    principal: UserId;
    name: string;
}
export interface SubmitQuizResult {
    attempt: QuizAttemptPublic;
    correctAnswers: Array<bigint>;
}
export interface Question {
    id: QuestionId;
    createdAt: Timestamp;
    text: string;
    subjectId: SubjectId;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export type SubjectId = bigint;
export interface Subject {
    id: SubjectId;
    name: string;
    createdAt: Timestamp;
    timerMinutes?: bigint;
    description: string;
}
export interface StudentSummary {
    principal: UserId;
    displayName: string;
    totalAttempts: bigint;
    averageScore: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createQuestion(payload: CreateQuestionPayload): Promise<Question>;
    createSubject(payload: CreateSubjectPayload): Promise<Subject>;
    deleteQuestion(id: QuestionId): Promise<boolean>;
    deleteSubject(id: SubjectId): Promise<boolean>;
    generateCertificateShareToken(subjectId: SubjectId): Promise<string | null>;
    getAllAttempts(): Promise<Array<QuizAttemptPublic>>;
    getAllStudentNames(): Promise<Array<StudentNameEntry>>;
    getAttemptDetails(attemptId: AttemptId): Promise<AttemptDetails | null>;
    getAttemptsByStudent(studentId: UserId): Promise<Array<QuizAttemptPublic>>;
    getAttemptsBySubject(subjectId: SubjectId): Promise<Array<QuizAttemptPublic>>;
    getCallerUserRole(): Promise<UserRole>;
    getCertificateByToken(token: string): Promise<Certificate | null>;
    getCertificates(): Promise<Array<Certificate>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyAttempts(): Promise<Array<QuizAttemptPublic>>;
    getMyProfile(): Promise<StudentProfilePublic>;
    getSubjectCertificate(subjectId: SubjectId): Promise<Certificate | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllStudents(): Promise<Array<StudentSummary>>;
    listQuestionsBySubject(subjectId: SubjectId): Promise<Array<QuestionPublic>>;
    listQuestionsWithAnswers(subjectId: SubjectId): Promise<Array<Question>>;
    listSubjects(): Promise<Array<SubjectWithStats>>;
    registerStudent(): Promise<StudentProfilePublic>;
    startQuiz(subjectId: SubjectId): Promise<QuizAttemptPublic>;
    submitQuizAnswers(payload: SubmitAnswersPayload): Promise<SubmitQuizResult>;
    updateMyAccentColor(color: string): Promise<boolean>;
    updateMyDepartment(value: string): Promise<boolean>;
    updateMyDisplayName(name: string): Promise<boolean>;
    updateMyEnrollNumber(value: string): Promise<boolean>;
    updateMyRegisterNumber(value: string): Promise<boolean>;
    updateMySection(value: string): Promise<boolean>;
    updateQuestion(payload: UpdateQuestionPayload): Promise<boolean>;
    updateSubject(payload: UpdateSubjectPayload): Promise<boolean>;
}
import type { AttemptDetails as _AttemptDetails, AttemptId as _AttemptId, Certificate as _Certificate, CreateSubjectPayload as _CreateSubjectPayload, QuizAttemptPublic as _QuizAttemptPublic, Subject as _Subject, SubjectId as _SubjectId, SubjectWithStats as _SubjectWithStats, SubmitQuizResult as _SubmitQuizResult, Timestamp as _Timestamp, UpdateSubjectPayload as _UpdateSubjectPayload, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createQuestion(arg0: CreateQuestionPayload): Promise<Question> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0);
            return result;
        }
    }
    async createSubject(arg0: CreateSubjectPayload): Promise<Subject> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(to_candid_CreateSubjectPayload_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Subject_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(to_candid_CreateSubjectPayload_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Subject_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteQuestion(arg0: QuestionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: SubjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async generateCertificateShareToken(arg0: SubjectId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCertificateShareToken(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCertificateShareToken(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAttempts(): Promise<Array<QuizAttemptPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttempts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttempts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudentNames(): Promise<Array<StudentNameEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentNames();
            return result;
        }
    }
    async getAttemptDetails(arg0: AttemptId): Promise<AttemptDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttemptDetails(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttemptDetails(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttemptsByStudent(arg0: UserId): Promise<Array<QuizAttemptPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttemptsByStudent(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttemptsByStudent(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttemptsBySubject(arg0: SubjectId): Promise<Array<QuizAttemptPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttemptsBySubject(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttemptsBySubject(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificateByToken(arg0: string): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificateByToken(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificateByToken(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificates();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyAttempts(): Promise<Array<QuizAttemptPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttempts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttempts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<StudentProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getSubjectCertificate(arg0: SubjectId): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectCertificate(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectCertificate(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllStudents(): Promise<Array<StudentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudents();
            return result;
        }
    }
    async listQuestionsBySubject(arg0: SubjectId): Promise<Array<QuestionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestionsBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestionsBySubject(arg0);
            return result;
        }
    }
    async listQuestionsWithAnswers(arg0: SubjectId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestionsWithAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestionsWithAnswers(arg0);
            return result;
        }
    }
    async listSubjects(): Promise<Array<SubjectWithStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStudent(): Promise<StudentProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent();
            return result;
        }
    }
    async startQuiz(arg0: SubjectId): Promise<QuizAttemptPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.startQuiz(arg0);
                return from_candid_QuizAttemptPublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startQuiz(arg0);
            return from_candid_QuizAttemptPublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizAnswers(arg0: SubmitAnswersPayload): Promise<SubmitQuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0);
                return from_candid_SubmitQuizResult_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0);
            return from_candid_SubmitQuizResult_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyAccentColor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyAccentColor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyAccentColor(arg0);
            return result;
        }
    }
    async updateMyDepartment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyDepartment(arg0);
            return result;
        }
    }
    async updateMyDisplayName(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyDisplayName(arg0);
            return result;
        }
    }
    async updateMyEnrollNumber(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyEnrollNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyEnrollNumber(arg0);
            return result;
        }
    }
    async updateMyRegisterNumber(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyRegisterNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyRegisterNumber(arg0);
            return result;
        }
    }
    async updateMySection(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMySection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMySection(arg0);
            return result;
        }
    }
    async updateQuestion(arg0: UpdateQuestionPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0);
            return result;
        }
    }
    async updateSubject(arg0: UpdateSubjectPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(to_candid_UpdateSubjectPayload_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(to_candid_UpdateSubjectPayload_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AttemptDetails_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttemptDetails): AttemptDetails {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_QuizAttemptPublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizAttemptPublic): QuizAttemptPublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectWithStats_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectWithStats): SubjectWithStats {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitQuizResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitQuizResult): SubmitQuizResult {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttemptDetails]): AttemptDetails | null {
    return value.length === 0 ? null : from_candid_AttemptDetails_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttemptId;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    answers: Array<bigint>;
    completed: boolean;
    studentPrincipal: _UserId;
    scorePercentage: bigint;
    score: bigint;
    totalQuestions: bigint;
    timeLimitMinutes: [] | [bigint];
    subjectId: _SubjectId;
}): {
    id: AttemptId;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    answers: Array<bigint>;
    completed: boolean;
    studentPrincipal: UserId;
    scorePercentage: bigint;
    score: bigint;
    totalQuestions: bigint;
    timeLimitMinutes?: bigint;
    subjectId: SubjectId;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: value.startedAt,
        answers: value.answers,
        completed: value.completed,
        studentPrincipal: value.studentPrincipal,
        scorePercentage: value.scorePercentage,
        score: value.score,
        totalQuestions: value.totalQuestions,
        timeLimitMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timeLimitMinutes)),
        subjectId: value.subjectId
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attempt: _QuizAttemptPublic;
    correctAnswers: Array<bigint>;
}): {
    attempt: QuizAttemptPublic;
    correctAnswers: Array<bigint>;
} {
    return {
        attempt: from_candid_QuizAttemptPublic_n10(_uploadFile, _downloadFile, value.attempt),
        correctAnswers: value.correctAnswers
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubjectId;
    name: string;
    createdAt: _Timestamp;
    timerMinutes: [] | [bigint];
    description: string;
    questionCount: bigint;
}): {
    id: SubjectId;
    name: string;
    createdAt: Timestamp;
    timerMinutes?: bigint;
    description: string;
    questionCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        timerMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timerMinutes)),
        description: value.description,
        questionCount: value.questionCount
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubjectId;
    name: string;
    createdAt: _Timestamp;
    timerMinutes: [] | [bigint];
    description: string;
}): {
    id: SubjectId;
    name: string;
    createdAt: Timestamp;
    timerMinutes?: bigint;
    description: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        timerMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timerMinutes)),
        description: value.description
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubjectWithStats>): Array<SubjectWithStats> {
    return value.map((x)=>from_candid_SubjectWithStats_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizAttemptPublic>): Array<QuizAttemptPublic> {
    return value.map((x)=>from_candid_QuizAttemptPublic_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CreateSubjectPayload_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateSubjectPayload): _CreateSubjectPayload {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSubjectPayload_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSubjectPayload): _UpdateSubjectPayload {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SubjectId;
    name: string;
    timerMinutes?: bigint;
    description: string;
}): {
    id: _SubjectId;
    name: string;
    timerMinutes: [] | [bigint];
    description: string;
} {
    return {
        id: value.id,
        name: value.name,
        timerMinutes: value.timerMinutes ? candid_some(value.timerMinutes) : candid_none(),
        description: value.description
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    timerMinutes?: bigint;
    description: string;
}): {
    name: string;
    timerMinutes: [] | [bigint];
    description: string;
} {
    return {
        name: value.name,
        timerMinutes: value.timerMinutes ? candid_some(value.timerMinutes) : candid_none(),
        description: value.description
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
